before:
  hooks:
    - go mod tidy

builds:
  - id: pdf-joiner
    main: .
    binary: pdf-joiner
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitTimestamp }}"
    no_unique_dist_dir: false
    overrides:
      - goos: linux
        goarch: amd64
        binary: pdf-joiner-linux-amd64
      - goos: linux
        goarch: arm64
        binary: pdf-joiner-linux-arm64
      - goos: darwin
        goarch: amd64
        binary: pdf-joiner-darwin-amd64
      - goos: darwin
        goarch: arm64
        binary: pdf-joiner-darwin-arm64

archives:
  - format: tar.gz
    name_template: "pdf-joiner-{{ .Os }}-{{ .Arch }}"
    files:
      - "README.md"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  draft: false
  prerelease: false