before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: "pdf-joiner-{{ .Os }}-{{ .Arch }}"
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "pdf-joiner-{{ .Os }}-{{ .Arch }}"
    files:
      - "README.md"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  draft: false
  prerelease: false 