before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    binary: "pdf-joiner-linux-amd64"
    ldflags:
      - -s -w

  - id: linux-arm64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    binary: "pdf-joiner-linux-arm64"
    ldflags:
      - -s -w

  - id: darwin-amd64
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    binary: "pdf-joiner-darwin-amd64"
    ldflags:
      - -s -w

  - id: darwin-arm64
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    binary: "pdf-joiner-darwin-arm64"
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "pdf-joiner-{{ .Os }}-{{ .Arch }}"
    files:
      - "README.md"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  draft: false
  prerelease: false 